enum ActivityType {
  NEW_COMMENT,
  // FOLLOW,
  NEW_LIKE,
  NEW_POST,
  NEW_SURVEY_SCHEDULED,
}

enum ContentType { INFORMATION, TREATMENT, ACADEMY, SUCCESS_STORIES }

enum QuestionType { BOOL, MULTIPLE, OPEN_SHORT, OPEN_LONG, SINGLE }

enum ModuleTab { KNOWLEDGE, THERAPY, RESEARCH, STORIES }

enum UserRole { ADMIN, PILOT, TEST, CONTROL, GUEST }

enum UserStatus { UNCONFIRMED, ADMIN, INTRODUCTION, TUTORIAL, FINAL }

typedef OnPressedButton = void Function();
