name: thesis_cancer
description: Womens' with Cancer's companion application.

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  audio_session: ^0.1.6+1
  badges: ^2.0.2
  better_player: ^0.0.81
  cached_network_image: ^3.2.0
  card_swiper: ^2.0.3
  cloud_firestore: ^3.1.12
  colorize: ^3.0.0
  # connectivity_plus: ^1.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

  device_info_plus: ^3.2.3
  dots_indicator: ^2.1.0
  enum_to_string: ^2.0.1
  file_picker: ^4.5.1
  firebase_analytics: ^9.1.5
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1
  firebase_messaging: ^11.2.13
  firebase_storage: ^10.2.12
  # fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.4.0
  flutter_cache_manager: ^3.3.0
  flutter_chat_types: ^3.3.4
  flutter_chat_ui: ^1.5.8
  flutter_firebase_chat_core: ^1.5.4
  flutter_form_builder: ^7.1.1
  flutter_hooks: ^0.18.0
  flutter_local_notifications: ^9.4.0
  flutter_localizations:
    sdk: flutter
  flutter_login: ^3.2.0
  flutter_markdown: ^0.6.10
  flutter_native_timezone: ^2.0.0
  flutter_svg: ^1.0.3
  # flutter_whatsnew: ^1.0.3
  form_builder_validators: ^8.1.0
  freezed_annotation: ^0.14.3
  graphql: ^5.0.1
  group_button: ^4.8.0
  hooks_riverpod: ^0.14.0+5
  http: ^0.13.4
  http_parser: ^4.0.0
  image_picker: ^0.8.5
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  json_annotation: ^4.3.0
  just_audio: ^0.9.20
  like_button: ^2.0.4
  mask_text_input_formatter: ^2.3.0
  mime: ^1.0.1
  open_file: ^3.2.1
  package_info_plus: ^1.4.2
  path_provider: ^2.0.9
  # permission_handler: ^6.1.1
  # pin_code_fields: ^7.0.0
  pull_to_refresh: ^2.0.0
  rxdart: ^0.27.3
  sembast: ^3.2.0
  timezone: ^0.8.0
  tutorial_coach_mark: ^1.2.1
  url_launcher: ^6.0.20
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  json_serializable: ^6.0.1
  lint: ^1.8.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/errors/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
