name: thesis_cancer
description: A new Cancer social and control application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  badges: ^2.0.1
  better_player: ^0.0.73
  cached_network_image: ^3.1.0
  card_swiper: ^1.0.4
  # carousel_slider: ^4.0.0-nullsafety.0
  cloud_firestore: ^2.5.1
  colorize: ^3.0.0
  # connectivity_plus: ^1.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  dots_indicator: ^2.0.0
  enum_to_string: ^2.0.1
  file_picker: ^4.0.2
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  firebase_storage: ^10.0.3
  # fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.2.0
  flutter_cache_manager: ^3.1.2
  flutter_chat_ui: ^1.3.3
  flutter_firebase_chat_core: ^1.3.1
  flutter_form_builder: ^6.1.0+1
  flutter_hooks: ^0.17.0
  flutter_local_notifications: ^8.1.1+2
  flutter_localizations:
    sdk: flutter
  flutter_login: ^2.2.1
  flutter_native_timezone: ^2.0.0
  flutter_svg: ^0.22.0
  # flutter_whatsnew: ^1.0.3
  form_field_validator: ^1.1.0
  freezed_annotation: ^0.14.2
  graphql: ^5.0.0
  group_button: ^3.1.0
  hooks_riverpod: ^0.14.0+4
  http_parser: ^4.0.0
  image_picker: ^0.8.4
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  like_button: ^2.0.3
  # material_design_icons_flutter: ^5.0.5955-rc.1
  mask_text_input_formatter: ^2.0.0
  mime: ^1.0.0
  open_file: ^3.2.1
  package_info_plus: ^1.0.6
  path_provider: ^2.0.3
  # permission_handler: ^6.1.1
  # pin_code_fields: ^7.0.0
  pull_to_refresh: ^2.0.0
  readmore: ^2.1.0
  # responsive: ^0.2.8+3
  rxdart: ^0.26.0
  sembast: ^3.1.0+2
  socket_io_client: ^1.0.1
  timezone: ^0.8.0
  tutorial_coach_mark: ^1.1.1
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  json_serializable: ^4.1.3
  lint: ^1.5.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/errors/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
